channels:
- defaults
dependencies:
- python=3.6.8
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19323974
  - azureml-defaults==0.1.0.19323974
  - azureml-pipeline-wrapper==0.1.0.19323974
name: project_environment
