# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AKSReplicaStatus(Model):
    """AKSReplicaStatus.

    :param desired_replicas:
    :type desired_replicas: int
    :param updated_replicas:
    :type updated_replicas: int
    :param available_replicas:
    :type available_replicas: int
    :param error:
    :type error: ~designer.models.AKSReplicaStatusError
    """

    _attribute_map = {
        'desired_replicas': {'key': 'desiredReplicas', 'type': 'int'},
        'updated_replicas': {'key': 'updatedReplicas', 'type': 'int'},
        'available_replicas': {'key': 'availableReplicas', 'type': 'int'},
        'error': {'key': 'error', 'type': 'AKSReplicaStatusError'},
    }

    def __init__(self, *, desired_replicas: int=None, updated_replicas: int=None, available_replicas: int=None, error=None, **kwargs) -> None:
        super(AKSReplicaStatus, self).__init__(**kwargs)
        self.desired_replicas = desired_replicas
        self.updated_replicas = updated_replicas
        self.available_replicas = available_replicas
        self.error = error
