# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureDatabaseReference(Model):
    """AzureDatabaseReference.

    :param table_name:
    :type table_name: str
    :param sql_query:
    :type sql_query: str
    :param stored_procedure_name:
    :type stored_procedure_name: str
    :param stored_procedure_parameters:
    :type stored_procedure_parameters:
     list[~designer.models.StoredProcedureParameter]
    :param aml_data_store_name:
    :type aml_data_store_name: str
    """

    _attribute_map = {
        'table_name': {'key': 'tableName', 'type': 'str'},
        'sql_query': {'key': 'sqlQuery', 'type': 'str'},
        'stored_procedure_name': {'key': 'storedProcedureName', 'type': 'str'},
        'stored_procedure_parameters': {'key': 'storedProcedureParameters', 'type': '[StoredProcedureParameter]'},
        'aml_data_store_name': {'key': 'amlDataStoreName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AzureDatabaseReference, self).__init__(**kwargs)
        self.table_name = kwargs.get('table_name', None)
        self.sql_query = kwargs.get('sql_query', None)
        self.stored_procedure_name = kwargs.get('stored_procedure_name', None)
        self.stored_procedure_parameters = kwargs.get('stored_procedure_parameters', None)
        self.aml_data_store_name = kwargs.get('aml_data_store_name', None)
