# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BatchGetModuleRequest(Model):
    """BatchGetModuleRequest.

    :param module_version_ids:
    :type module_version_ids: list[str]
    :param aml_modules:
    :type aml_modules: list[~designer.models.AmlModuleNameMetaInfo]
    """

    _attribute_map = {
        'module_version_ids': {'key': 'moduleVersionIds', 'type': '[str]'},
        'aml_modules': {'key': 'amlModules', 'type': '[AmlModuleNameMetaInfo]'},
    }

    def __init__(self, **kwargs):
        super(BatchGetModuleRequest, self).__init__(**kwargs)
        self.module_version_ids = kwargs.get('module_version_ids', None)
        self.aml_modules = kwargs.get('aml_modules', None)
