# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CloudSettings(Model):
    """CloudSettings.

    :param hdi_run_config:
    :type hdi_run_config: ~designer.models.CloudSettingsHdiRunConfig
    """

    _attribute_map = {
        'hdi_run_config': {'key': 'hdiRunConfig', 'type': 'CloudSettingsHdiRunConfig'},
    }

    def __init__(self, **kwargs):
        super(CloudSettings, self).__init__(**kwargs)
        self.hdi_run_config = kwargs.get('hdi_run_config', None)
