# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .run_setting_ui_parameter_hint_py3 import RunSettingUIParameterHint


class ComputeRunSettingParameterRunSettingUIHint(RunSettingUIParameterHint):
    """ComputeRunSettingParameterRunSettingUIHint.

    :param ui_widget_type: Possible values include: 'Default',
     'ComputeSelection', 'JsonEditor'
    :type ui_widget_type: str or ~designer.models.RunSettingUIWidgetTypeEnum
    :param json_editor:
    :type json_editor: ~designer.models.RunSettingUIParameterHintJsonEditor
    :param compute_selection:
    :type compute_selection:
     ~designer.models.RunSettingUIParameterHintComputeSelection
    """

    _attribute_map = {
        'ui_widget_type': {'key': 'uiWidgetType', 'type': 'str'},
        'json_editor': {'key': 'jsonEditor', 'type': 'RunSettingUIParameterHintJsonEditor'},
        'compute_selection': {'key': 'computeSelection', 'type': 'RunSettingUIParameterHintComputeSelection'},
    }

    def __init__(self, *, ui_widget_type=None, json_editor=None, compute_selection=None, **kwargs) -> None:
        super(ComputeRunSettingParameterRunSettingUIHint, self).__init__(ui_widget_type=ui_widget_type, json_editor=json_editor, compute_selection=compute_selection, **kwargs)
