# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CreateInferencePipelineRequest(Model):
    """CreateInferencePipelineRequest.

    :param module_node_id:
    :type module_node_id: str
    :param port_name:
    :type port_name: str
    :param training_pipeline_draft_name:
    :type training_pipeline_draft_name: str
    :param name:
    :type name: str
    :param description:
    :type description: str
    :param pipeline_type: Possible values include: 'TrainingPipeline',
     'RealTimeInferencePipeline', 'BatchInferencePipeline', 'Unknown'
    :type pipeline_type: str or ~designer.models.PipelineType
    :param pipeline_draft_mode: Possible values include: 'None', 'Normal',
     'Custom'
    :type pipeline_draft_mode: str or ~designer.models.PipelineDraftMode
    :param graph:
    :type graph: ~designer.models.CreateInferencePipelineRequestGraph
    :param tags: This is a dictionary
    :type tags: dict[str, str]
    :param properties: This is a dictionary
    :type properties: dict[str, str]
    :param sub_pipelines_info:
    :type sub_pipelines_info:
     ~designer.models.CreateInferencePipelineRequestSubPipelinesInfo
    """

    _attribute_map = {
        'module_node_id': {'key': 'moduleNodeId', 'type': 'str'},
        'port_name': {'key': 'portName', 'type': 'str'},
        'training_pipeline_draft_name': {'key': 'trainingPipelineDraftName', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'pipeline_type': {'key': 'pipelineType', 'type': 'str'},
        'pipeline_draft_mode': {'key': 'pipelineDraftMode', 'type': 'str'},
        'graph': {'key': 'graph', 'type': 'CreateInferencePipelineRequestGraph'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'sub_pipelines_info': {'key': 'subPipelinesInfo', 'type': 'CreateInferencePipelineRequestSubPipelinesInfo'},
    }

    def __init__(self, *, module_node_id: str=None, port_name: str=None, training_pipeline_draft_name: str=None, name: str=None, description: str=None, pipeline_type=None, pipeline_draft_mode=None, graph=None, tags=None, properties=None, sub_pipelines_info=None, **kwargs) -> None:
        super(CreateInferencePipelineRequest, self).__init__(**kwargs)
        self.module_node_id = module_node_id
        self.port_name = port_name
        self.training_pipeline_draft_name = training_pipeline_draft_name
        self.name = name
        self.description = description
        self.pipeline_type = pipeline_type
        self.pipeline_draft_mode = pipeline_draft_mode
        self.graph = graph
        self.tags = tags
        self.properties = properties
        self.sub_pipelines_info = sub_pipelines_info
