# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_data_lake_gen2_reference import AzureDataLakeGen2Reference


class DataReferenceAzureDataLakeGen2Reference(AzureDataLakeGen2Reference):
    """DataReferenceAzureDataLakeGen2Reference.

    :param file_system_name:
    :type file_system_name: str
    :param uri:
    :type uri: str
    :param account:
    :type account: str
    :param relative_path:
    :type relative_path: str
    :param aml_data_store_name:
    :type aml_data_store_name: str
    """

    _attribute_map = {
        'file_system_name': {'key': 'fileSystemName', 'type': 'str'},
        'uri': {'key': 'uri', 'type': 'str'},
        'account': {'key': 'account', 'type': 'str'},
        'relative_path': {'key': 'relativePath', 'type': 'str'},
        'aml_data_store_name': {'key': 'amlDataStoreName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DataReferenceAzureDataLakeGen2Reference, self).__init__(**kwargs)
