# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataSetDefinitionValue(Model):
    """DataSetDefinitionValue.

    :param literal_value:
    :type literal_value: ~designer.models.DataSetDefinitionValueLiteralValue
    :param data_set_reference:
    :type data_set_reference:
     ~designer.models.DataSetDefinitionValueDataSetReference
    :param saved_data_set_reference:
    :type saved_data_set_reference:
     ~designer.models.DataSetDefinitionValueSavedDataSetReference
    """

    _attribute_map = {
        'literal_value': {'key': 'literalValue', 'type': 'DataSetDefinitionValueLiteralValue'},
        'data_set_reference': {'key': 'dataSetReference', 'type': 'DataSetDefinitionValueDataSetReference'},
        'saved_data_set_reference': {'key': 'savedDataSetReference', 'type': 'DataSetDefinitionValueSavedDataSetReference'},
    }

    def __init__(self, **kwargs):
        super(DataSetDefinitionValue, self).__init__(**kwargs)
        self.literal_value = kwargs.get('literal_value', None)
        self.data_set_reference = kwargs.get('data_set_reference', None)
        self.saved_data_set_reference = kwargs.get('saved_data_set_reference', None)
