# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_blob_reference import AzureBlobReference


class DataReferenceAzureBlobReference(AzureBlobReference):
    """DataReferenceAzureBlobReference.

    :param container:
    :type container: str
    :param sas_token:
    :type sas_token: str
    :param uri:
    :type uri: str
    :param account:
    :type account: str
    :param relative_path:
    :type relative_path: str
    :param aml_data_store_name:
    :type aml_data_store_name: str
    """

    _attribute_map = {
        'container': {'key': 'container', 'type': 'str'},
        'sas_token': {'key': 'sasToken', 'type': 'str'},
        'uri': {'key': 'uri', 'type': 'str'},
        'account': {'key': 'account', 'type': 'str'},
        'relative_path': {'key': 'relativePath', 'type': 'str'},
        'aml_data_store_name': {'key': 'amlDataStoreName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DataReferenceAzureBlobReference, self).__init__(**kwargs)
