# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataPathParameter(Model):
    """DataPathParameter.

    :param name:
    :type name: str
    :param documentation:
    :type documentation: str
    :param default_value:
    :type default_value: ~designer.models.DataPathParameterDefaultValue
    :param is_optional:
    :type is_optional: bool
    :param data_type_id:
    :type data_type_id: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'documentation': {'key': 'documentation', 'type': 'str'},
        'default_value': {'key': 'defaultValue', 'type': 'DataPathParameterDefaultValue'},
        'is_optional': {'key': 'isOptional', 'type': 'bool'},
        'data_type_id': {'key': 'dataTypeId', 'type': 'str'},
    }

    def __init__(self, *, name: str=None, documentation: str=None, default_value=None, is_optional: bool=None, data_type_id: str=None, **kwargs) -> None:
        super(DataPathParameter, self).__init__(**kwargs)
        self.name = name
        self.documentation = documentation
        self.default_value = default_value
        self.is_optional = is_optional
        self.data_type_id = data_type_id
