# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .dbfs_reference import DBFSReference


class DataReferenceDbfsReference(DBFSReference):
    """DataReferenceDbfsReference.

    :param relative_path:
    :type relative_path: str
    :param aml_data_store_name:
    :type aml_data_store_name: str
    """

    _attribute_map = {
        'relative_path': {'key': 'relativePath', 'type': 'str'},
        'aml_data_store_name': {'key': 'amlDataStoreName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DataReferenceDbfsReference, self).__init__(**kwargs)
