# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .saved_data_set_reference_py3 import SavedDataSetReference


class DataSetDefinitionValueSavedDataSetReference(SavedDataSetReference):
    """DataSetDefinitionValueSavedDataSetReference.

    :param id:
    :type id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, **kwargs) -> None:
        super(DataSetDefinitionValueSavedDataSetReference, self).__init__(id=id, **kwargs)
