# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DBFSReference(Model):
    """DBFSReference.

    :param relative_path:
    :type relative_path: str
    :param aml_data_store_name:
    :type aml_data_store_name: str
    """

    _attribute_map = {
        'relative_path': {'key': 'relativePath', 'type': 'str'},
        'aml_data_store_name': {'key': 'amlDataStoreName', 'type': 'str'},
    }

    def __init__(self, *, relative_path: str=None, aml_data_store_name: str=None, **kwargs) -> None:
        super(DBFSReference, self).__init__(**kwargs)
        self.relative_path = relative_path
        self.aml_data_store_name = aml_data_store_name
