# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeploymentInfo(Model):
    """DeploymentInfo.

    :param operation_id:
    :type operation_id: str
    :param service_id:
    :type service_id: str
    :param service_name:
    :type service_name: str
    :param status_detail:
    :type status_detail: str
    """

    _attribute_map = {
        'operation_id': {'key': 'operationId', 'type': 'str'},
        'service_id': {'key': 'serviceId', 'type': 'str'},
        'service_name': {'key': 'serviceName', 'type': 'str'},
        'status_detail': {'key': 'statusDetail', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DeploymentInfo, self).__init__(**kwargs)
        self.operation_id = kwargs.get('operation_id', None)
        self.service_id = kwargs.get('service_id', None)
        self.service_name = kwargs.get('service_name', None)
        self.status_detail = kwargs.get('status_detail', None)
