# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .root_error_py3 import RootError


class ErrorResponseError(RootError):
    """ErrorResponseError.

    :param code:
    :type code: str
    :param message:
    :type message: str
    :param message_format:
    :type message_format: str
    :param message_parameters:
    :type message_parameters: dict[str, str]
    :param reference_code:
    :type reference_code: str
    :param details_uri:
    :type details_uri: str
    :param target:
    :type target: str
    :param details:
    :type details: list[~designer.models.RootError]
    :param inner_error:
    :type inner_error: ~designer.models.RootErrorInnerError
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'message_format': {'key': 'messageFormat', 'type': 'str'},
        'message_parameters': {'key': 'messageParameters', 'type': '{str}'},
        'reference_code': {'key': 'referenceCode', 'type': 'str'},
        'details_uri': {'key': 'detailsUri', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[RootError]'},
        'inner_error': {'key': 'innerError', 'type': 'RootErrorInnerError'},
    }

    def __init__(self, *, code: str=None, message: str=None, message_format: str=None, message_parameters=None, reference_code: str=None, details_uri: str=None, target: str=None, details=None, inner_error=None, **kwargs) -> None:
        super(ErrorResponseError, self).__init__(code=code, message=message, message_format=message_format, message_parameters=message_parameters, reference_code=reference_code, details_uri=details_uri, target=target, details=details, inner_error=inner_error, **kwargs)
