# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GraphEdge(Model):
    """GraphEdge.

    :param source_output_port:
    :type source_output_port: ~designer.models.GraphEdgeSourceOutputPort
    :param destination_input_port:
    :type destination_input_port:
     ~designer.models.GraphEdgeDestinationInputPort
    """

    _attribute_map = {
        'source_output_port': {'key': 'sourceOutputPort', 'type': 'GraphEdgeSourceOutputPort'},
        'destination_input_port': {'key': 'destinationInputPort', 'type': 'GraphEdgeDestinationInputPort'},
    }

    def __init__(self, **kwargs):
        super(GraphEdge, self).__init__(**kwargs)
        self.source_output_port = kwargs.get('source_output_port', None)
        self.destination_input_port = kwargs.get('destination_input_port', None)
