# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .cloud_settings import CloudSettings


class GraphModuleNodeCloudSettings(CloudSettings):
    """GraphModuleNodeCloudSettings.

    :param hdi_run_config:
    :type hdi_run_config: ~designer.models.CloudSettingsHdiRunConfig
    """

    _attribute_map = {
        'hdi_run_config': {'key': 'hdiRunConfig', 'type': 'CloudSettingsHdiRunConfig'},
    }

    def __init__(self, **kwargs):
        super(GraphModuleNodeCloudSettings, self).__init__(**kwargs)
