# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .inner_error_response import InnerErrorResponse


class InnerErrorResponseInnerError(InnerErrorResponse):
    """InnerErrorResponseInnerError.

    :param code:
    :type code: str
    :param inner_error:
    :type inner_error: ~designer.models.InnerErrorResponseInnerError
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'inner_error': {'key': 'innerError', 'type': 'InnerErrorResponseInnerError'},
    }

    def __init__(self, **kwargs):
        super(InnerErrorResponseInnerError, self).__init__(**kwargs)
