# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ModelManagementErrorResponse(Model):
    """ModelManagementErrorResponse.

    :param code:
    :type code: str
    :param status_code:
    :type status_code: int
    :param message:
    :type message: str
    :param details:
    :type details: list[~designer.models.InnerErrorDetails]
    :param correlation:
    :type correlation: dict[str, str]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'status_code': {'key': 'statusCode', 'type': 'int'},
        'message': {'key': 'message', 'type': 'str'},
        'details': {'key': 'details', 'type': '[InnerErrorDetails]'},
        'correlation': {'key': 'correlation', 'type': '{str}'},
    }

    def __init__(self, *, code: str=None, status_code: int=None, message: str=None, details=None, correlation=None, **kwargs) -> None:
        super(ModelManagementErrorResponse, self).__init__(**kwargs)
        self.code = code
        self.status_code = status_code
        self.message = message
        self.details = details
        self.correlation = correlation
