# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .cloud_settings_py3 import CloudSettings


class ModuleEntityCloudSettings(CloudSettings):
    """ModuleEntityCloudSettings.

    :param hdi_run_config:
    :type hdi_run_config: ~designer.models.CloudSettingsHdiRunConfig
    """

    _attribute_map = {
        'hdi_run_config': {'key': 'hdiRunConfig', 'type': 'CloudSettingsHdiRunConfig'},
    }

    def __init__(self, *, hdi_run_config=None, **kwargs) -> None:
        super(ModuleEntityCloudSettings, self).__init__(hdi_run_config=hdi_run_config, **kwargs)
