# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NodeInputPort(Model):
    """NodeInputPort.

    :param name:
    :type name: str
    :param documentation:
    :type documentation: str
    :param data_types_ids:
    :type data_types_ids: list[str]
    :param is_optional:
    :type is_optional: bool
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'documentation': {'key': 'documentation', 'type': 'str'},
        'data_types_ids': {'key': 'dataTypesIds', 'type': '[str]'},
        'is_optional': {'key': 'isOptional', 'type': 'bool'},
    }

    def __init__(self, *, name: str=None, documentation: str=None, data_types_ids=None, is_optional: bool=None, **kwargs) -> None:
        super(NodeInputPort, self).__init__(**kwargs)
        self.name = name
        self.documentation = documentation
        self.data_types_ids = data_types_ids
        self.is_optional = is_optional
