# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NodePortInterface(Model):
    """NodePortInterface.

    :param inputs:
    :type inputs: list[~designer.models.NodeInputPort]
    :param outputs:
    :type outputs: list[~designer.models.NodeOutputPort]
    """

    _attribute_map = {
        'inputs': {'key': 'inputs', 'type': '[NodeInputPort]'},
        'outputs': {'key': 'outputs', 'type': '[NodeOutputPort]'},
    }

    def __init__(self, *, inputs=None, outputs=None, **kwargs) -> None:
        super(NodePortInterface, self).__init__(**kwargs)
        self.inputs = inputs
        self.outputs = outputs
