# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class OutputSetting(Model):
    """OutputSetting.

    :param name:
    :type name: str
    :param data_store_name:
    :type data_store_name: str
    :param data_store_mode: Possible values include: 'None', 'Mount',
     'Download', 'Upload', 'Direct', 'Hdfs'
    :type data_store_mode: str or ~designer.models.DataStoreMode
    :param path_on_compute:
    :type path_on_compute: str
    :param overwrite:
    :type overwrite: bool
    :param data_reference_name:
    :type data_reference_name: str
    :param web_service_port:
    :type web_service_port: str
    :param dataset_registration:
    :type dataset_registration:
     ~designer.models.OutputSettingDatasetRegistration
    :param dataset_output_options:
    :type dataset_output_options:
     ~designer.models.OutputSettingDatasetOutputOptions
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'data_store_name': {'key': 'dataStoreName', 'type': 'str'},
        'data_store_mode': {'key': 'dataStoreMode', 'type': 'str'},
        'path_on_compute': {'key': 'pathOnCompute', 'type': 'str'},
        'overwrite': {'key': 'overwrite', 'type': 'bool'},
        'data_reference_name': {'key': 'dataReferenceName', 'type': 'str'},
        'web_service_port': {'key': 'webServicePort', 'type': 'str'},
        'dataset_registration': {'key': 'datasetRegistration', 'type': 'OutputSettingDatasetRegistration'},
        'dataset_output_options': {'key': 'datasetOutputOptions', 'type': 'OutputSettingDatasetOutputOptions'},
    }

    def __init__(self, *, name: str=None, data_store_name: str=None, data_store_mode=None, path_on_compute: str=None, overwrite: bool=None, data_reference_name: str=None, web_service_port: str=None, dataset_registration=None, dataset_output_options=None, **kwargs) -> None:
        super(OutputSetting, self).__init__(**kwargs)
        self.name = name
        self.data_store_name = data_store_name
        self.data_store_mode = data_store_mode
        self.path_on_compute = path_on_compute
        self.overwrite = overwrite
        self.data_reference_name = data_reference_name
        self.web_service_port = web_service_port
        self.dataset_registration = dataset_registration
        self.dataset_output_options = dataset_output_options
