# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Owner(Model):
    """Owner.

    :param owner_type: Possible values include: 'Undefined', 'User', 'Company'
    :type owner_type: str or ~designer.models.OwnerType
    :param id:
    :type id: str
    :param name:
    :type name: str
    :param avatar_url:
    :type avatar_url: str
    """

    _attribute_map = {
        'owner_type': {'key': 'owner_type', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'avatar_url': {'key': 'avatar_url', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Owner, self).__init__(**kwargs)
        self.owner_type = kwargs.get('owner_type', None)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.avatar_url = kwargs.get('avatar_url', None)
