# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PipelineRunGraphDetail(Model):
    """PipelineRunGraphDetail.

    :param graph:
    :type graph: ~designer.models.PipelineRunGraphDetailGraph
    :param graph_nodes_status: This is a dictionary
    :type graph_nodes_status: dict[str, ~designer.models.GraphNodeStatusInfo]
    """

    _attribute_map = {
        'graph': {'key': 'graph', 'type': 'PipelineRunGraphDetailGraph'},
        'graph_nodes_status': {'key': 'graphNodesStatus', 'type': '{GraphNodeStatusInfo}'},
    }

    def __init__(self, *, graph=None, graph_nodes_status=None, **kwargs) -> None:
        super(PipelineRunGraphDetail, self).__init__(**kwargs)
        self.graph = graph
        self.graph_nodes_status = graph_nodes_status
