# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .compute_setting_py3 import ComputeSetting


class PipelineGraphDefaultCompute(ComputeSetting):
    """PipelineGraphDefaultCompute.

    :param name:
    :type name: str
    :param compute_type: Possible values include: 'BatchAi', 'MLC',
     'HdiCluster', 'RemoteDocker', 'Databricks'
    :type compute_type: str or ~designer.models.ComputeType
    :param batch_ai_compute_info:
    :type batch_ai_compute_info:
     ~designer.models.ComputeSettingBatchAiComputeInfo
    :param remote_docker_compute_info:
    :type remote_docker_compute_info:
     ~designer.models.ComputeSettingRemoteDockerComputeInfo
    :param hdi_cluster_compute_info:
    :type hdi_cluster_compute_info:
     ~designer.models.ComputeSettingHdiClusterComputeInfo
    :param mlc_compute_info:
    :type mlc_compute_info: ~designer.models.ComputeSettingMlcComputeInfo
    :param databricks_compute_info:
    :type databricks_compute_info:
     ~designer.models.ComputeSettingDatabricksComputeInfo
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'compute_type': {'key': 'computeType', 'type': 'str'},
        'batch_ai_compute_info': {'key': 'batchAiComputeInfo', 'type': 'ComputeSettingBatchAiComputeInfo'},
        'remote_docker_compute_info': {'key': 'remoteDockerComputeInfo', 'type': 'ComputeSettingRemoteDockerComputeInfo'},
        'hdi_cluster_compute_info': {'key': 'hdiClusterComputeInfo', 'type': 'ComputeSettingHdiClusterComputeInfo'},
        'mlc_compute_info': {'key': 'mlcComputeInfo', 'type': 'ComputeSettingMlcComputeInfo'},
        'databricks_compute_info': {'key': 'databricksComputeInfo', 'type': 'ComputeSettingDatabricksComputeInfo'},
    }

    def __init__(self, *, name: str=None, compute_type=None, batch_ai_compute_info=None, remote_docker_compute_info=None, hdi_cluster_compute_info=None, mlc_compute_info=None, databricks_compute_info=None, **kwargs) -> None:
        super(PipelineGraphDefaultCompute, self).__init__(name=name, compute_type=compute_type, batch_ai_compute_info=batch_ai_compute_info, remote_docker_compute_info=remote_docker_compute_info, hdi_cluster_compute_info=hdi_cluster_compute_info, mlc_compute_info=mlc_compute_info, databricks_compute_info=databricks_compute_info, **kwargs)
