# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PipelineGraph(Model):
    """PipelineGraph.

    :param graph_modules:
    :type graph_modules: list[~designer.models.ModuleEntity]
    :param graph_module_dtos:
    :type graph_module_dtos: list[~designer.models.ModuleDto]
    :param graph_data_sources:
    :type graph_data_sources: list[~designer.models.DataInfo]
    :param module_node_run_settings:
    :type module_node_run_settings:
     list[~designer.models.GraphModuleNodeRunSetting]
    :param sub_pipelines_info:
    :type sub_pipelines_info: ~designer.models.PipelineGraphSubPipelinesInfo
    :param module_nodes:
    :type module_nodes: list[~designer.models.GraphModuleNode]
    :param dataset_nodes:
    :type dataset_nodes: list[~designer.models.GraphDatasetNode]
    :param edges:
    :type edges: list[~designer.models.GraphEdge]
    :param entity_interface:
    :type entity_interface: ~designer.models.PipelineGraphEntityInterface
    :param graph_layout:
    :type graph_layout: ~designer.models.PipelineGraphGraphLayout
    :param created_by:
    :type created_by: ~designer.models.PipelineGraphCreatedBy
    :param last_updated_by:
    :type last_updated_by: ~designer.models.PipelineGraphLastUpdatedBy
    :param default_compute:
    :type default_compute: ~designer.models.PipelineGraphDefaultCompute
    :param default_datastore:
    :type default_datastore: ~designer.models.PipelineGraphDefaultDatastore
    :param id:
    :type id: str
    :param etag:
    :type etag: str
    :param created_date:
    :type created_date: datetime
    :param last_modified_date:
    :type last_modified_date: datetime
    """

    _attribute_map = {
        'graph_modules': {'key': 'graphModules', 'type': '[ModuleEntity]'},
        'graph_module_dtos': {'key': 'graphModuleDtos', 'type': '[ModuleDto]'},
        'graph_data_sources': {'key': 'graphDataSources', 'type': '[DataInfo]'},
        'module_node_run_settings': {'key': 'moduleNodeRunSettings', 'type': '[GraphModuleNodeRunSetting]'},
        'sub_pipelines_info': {'key': 'subPipelinesInfo', 'type': 'PipelineGraphSubPipelinesInfo'},
        'module_nodes': {'key': 'moduleNodes', 'type': '[GraphModuleNode]'},
        'dataset_nodes': {'key': 'datasetNodes', 'type': '[GraphDatasetNode]'},
        'edges': {'key': 'edges', 'type': '[GraphEdge]'},
        'entity_interface': {'key': 'entityInterface', 'type': 'PipelineGraphEntityInterface'},
        'graph_layout': {'key': 'graphLayout', 'type': 'PipelineGraphGraphLayout'},
        'created_by': {'key': 'createdBy', 'type': 'PipelineGraphCreatedBy'},
        'last_updated_by': {'key': 'lastUpdatedBy', 'type': 'PipelineGraphLastUpdatedBy'},
        'default_compute': {'key': 'defaultCompute', 'type': 'PipelineGraphDefaultCompute'},
        'default_datastore': {'key': 'defaultDatastore', 'type': 'PipelineGraphDefaultDatastore'},
        'id': {'key': 'id', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'last_modified_date': {'key': 'lastModifiedDate', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(PipelineGraph, self).__init__(**kwargs)
        self.graph_modules = kwargs.get('graph_modules', None)
        self.graph_module_dtos = kwargs.get('graph_module_dtos', None)
        self.graph_data_sources = kwargs.get('graph_data_sources', None)
        self.module_node_run_settings = kwargs.get('module_node_run_settings', None)
        self.sub_pipelines_info = kwargs.get('sub_pipelines_info', None)
        self.module_nodes = kwargs.get('module_nodes', None)
        self.dataset_nodes = kwargs.get('dataset_nodes', None)
        self.edges = kwargs.get('edges', None)
        self.entity_interface = kwargs.get('entity_interface', None)
        self.graph_layout = kwargs.get('graph_layout', None)
        self.created_by = kwargs.get('created_by', None)
        self.last_updated_by = kwargs.get('last_updated_by', None)
        self.default_compute = kwargs.get('default_compute', None)
        self.default_datastore = kwargs.get('default_datastore', None)
        self.id = kwargs.get('id', None)
        self.etag = kwargs.get('etag', None)
        self.created_date = kwargs.get('created_date', None)
        self.last_modified_date = kwargs.get('last_modified_date', None)
