# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PipelineEndpoint(Model):
    """PipelineEndpoint.

    :param default_version:
    :type default_version: str
    :param default_pipeline_id:
    :type default_pipeline_id: str
    :param default_graph_id:
    :type default_graph_id: str
    :param rest_endpoint:
    :type rest_endpoint: str
    :param published_date:
    :type published_date: datetime
    :param published_by:
    :type published_by: str
    :param last_run_time:
    :type last_run_time: datetime
    :param last_run_status: Possible values include: 'NotStarted', 'Running',
     'Failed', 'Finished', 'Canceled'
    :type last_run_status: str or ~designer.models.PipelineRunStatusCode
    :param parameters: This is a dictionary
    :type parameters: dict[str, str]
    :param default_pipeline_name:
    :type default_pipeline_name: str
    :param name:
    :type name: str
    :param description:
    :type description: str
    :param updated_by:
    :type updated_by: str
    :param tags: This is a dictionary
    :type tags: dict[str, str]
    :param entity_status: Possible values include: 'Active', 'Deprecated',
     'Disabled'
    :type entity_status: str or ~designer.models.EntityStatus
    :param id:
    :type id: str
    :param etag:
    :type etag: str
    :param created_date:
    :type created_date: datetime
    :param last_modified_date:
    :type last_modified_date: datetime
    """

    _attribute_map = {
        'default_version': {'key': 'defaultVersion', 'type': 'str'},
        'default_pipeline_id': {'key': 'defaultPipelineId', 'type': 'str'},
        'default_graph_id': {'key': 'defaultGraphId', 'type': 'str'},
        'rest_endpoint': {'key': 'restEndpoint', 'type': 'str'},
        'published_date': {'key': 'publishedDate', 'type': 'iso-8601'},
        'published_by': {'key': 'publishedBy', 'type': 'str'},
        'last_run_time': {'key': 'lastRunTime', 'type': 'iso-8601'},
        'last_run_status': {'key': 'lastRunStatus', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '{str}'},
        'default_pipeline_name': {'key': 'defaultPipelineName', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'updated_by': {'key': 'updatedBy', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'entity_status': {'key': 'entityStatus', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'last_modified_date': {'key': 'lastModifiedDate', 'type': 'iso-8601'},
    }

    def __init__(self, *, default_version: str=None, default_pipeline_id: str=None, default_graph_id: str=None, rest_endpoint: str=None, published_date=None, published_by: str=None, last_run_time=None, last_run_status=None, parameters=None, default_pipeline_name: str=None, name: str=None, description: str=None, updated_by: str=None, tags=None, entity_status=None, id: str=None, etag: str=None, created_date=None, last_modified_date=None, **kwargs) -> None:
        super(PipelineEndpoint, self).__init__(**kwargs)
        self.default_version = default_version
        self.default_pipeline_id = default_pipeline_id
        self.default_graph_id = default_graph_id
        self.rest_endpoint = rest_endpoint
        self.published_date = published_date
        self.published_by = published_by
        self.last_run_time = last_run_time
        self.last_run_status = last_run_status
        self.parameters = parameters
        self.default_pipeline_name = default_pipeline_name
        self.name = name
        self.description = description
        self.updated_by = updated_by
        self.tags = tags
        self.entity_status = entity_status
        self.id = id
        self.etag = etag
        self.created_date = created_date
        self.last_modified_date = last_modified_date
