# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PipelineStepRunOutputs(Model):
    """PipelineStepRunOutputs.

    :param outputs: This is a dictionary
    :type outputs: dict[str, str]
    :param port_outputs: This is a dictionary
    :type port_outputs: dict[str, ~designer.models.PortOutputInfo]
    """

    _attribute_map = {
        'outputs': {'key': 'outputs', 'type': '{str}'},
        'port_outputs': {'key': 'portOutputs', 'type': '{PortOutputInfo}'},
    }

    def __init__(self, *, outputs=None, port_outputs=None, **kwargs) -> None:
        super(PipelineStepRunOutputs, self).__init__(**kwargs)
        self.outputs = outputs
        self.port_outputs = port_outputs
