# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PortOutputInfo(Model):
    """PortOutputInfo.

    :param container_uri:
    :type container_uri: str
    :param relative_path:
    :type relative_path: str
    :param data_store_name:
    :type data_store_name: str
    :param supported_actions:
    :type supported_actions: list[str or ~designer.models.PortAction]
    """

    _attribute_map = {
        'container_uri': {'key': 'containerUri', 'type': 'str'},
        'relative_path': {'key': 'relativePath', 'type': 'str'},
        'data_store_name': {'key': 'dataStoreName', 'type': 'str'},
        'supported_actions': {'key': 'supportedActions', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(PortOutputInfo, self).__init__(**kwargs)
        self.container_uri = kwargs.get('container_uri', None)
        self.relative_path = kwargs.get('relative_path', None)
        self.data_store_name = kwargs.get('data_store_name', None)
        self.supported_actions = kwargs.get('supported_actions', None)
