# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PythonInterfaceMapping(Model):
    """PythonInterfaceMapping.

    :param name:
    :type name: str
    :param argument_name:
    :type argument_name: str
    :param command_line_option:
    :type command_line_option: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'argument_name': {'key': 'argumentName', 'type': 'str'},
        'command_line_option': {'key': 'commandLineOption', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(PythonInterfaceMapping, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.argument_name = kwargs.get('argument_name', None)
        self.command_line_option = kwargs.get('command_line_option', None)
