# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegisterModuleMetaInfo(Model):
    """RegisterModuleMetaInfo.

    :param namespace:
    :type namespace: str
    :param module_name:
    :type module_name: str
    :param module_version:
    :type module_version: str
    :param module_entity_from_yaml:
    :type module_entity_from_yaml:
     ~designer.models.RegisterModuleMetaInfoModuleEntityFromYaml
    :param set_as_default_version:
    :type set_as_default_version: bool
    """

    _attribute_map = {
        'namespace': {'key': 'namespace', 'type': 'str'},
        'module_name': {'key': 'moduleName', 'type': 'str'},
        'module_version': {'key': 'moduleVersion', 'type': 'str'},
        'module_entity_from_yaml': {'key': 'moduleEntityFromYaml', 'type': 'RegisterModuleMetaInfoModuleEntityFromYaml'},
        'set_as_default_version': {'key': 'setAsDefaultVersion', 'type': 'bool'},
    }

    def __init__(self, **kwargs):
        super(RegisterModuleMetaInfo, self).__init__(**kwargs)
        self.namespace = kwargs.get('namespace', None)
        self.module_name = kwargs.get('module_name', None)
        self.module_version = kwargs.get('module_version', None)
        self.module_entity_from_yaml = kwargs.get('module_entity_from_yaml', None)
        self.set_as_default_version = kwargs.get('set_as_default_version', None)
