# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .ui_compute_selection import UIComputeSelection


class RunSettingUIParameterHintComputeSelection(UIComputeSelection):
    """RunSettingUIParameterHintComputeSelection.

    :param compute_types:
    :type compute_types: list[str]
    :param require_gpu:
    :type require_gpu: bool
    :param os_types:
    :type os_types: list[str]
    :param compute_run_settings_mapping:
    :type compute_run_settings_mapping: dict[str,
     list[~designer.models.ComputeRunSettingParameter]]
    """

    _attribute_map = {
        'compute_types': {'key': 'computeTypes', 'type': '[str]'},
        'require_gpu': {'key': 'requireGpu', 'type': 'bool'},
        'os_types': {'key': 'osTypes', 'type': '[str]'},
        'compute_run_settings_mapping': {'key': 'computeRunSettingsMapping', 'type': '{[ComputeRunSettingParameter]}'},
    }

    def __init__(self, **kwargs):
        super(RunSettingUIParameterHintComputeSelection, self).__init__(**kwargs)
