# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SnapshotInfo(Model):
    """SnapshotInfo.

    :param root_download_url:
    :type root_download_url: str
    :param snapshots: This is a dictionary
    :type snapshots: dict[str, ~designer.models.DownloadResourceInfo]
    """

    _attribute_map = {
        'root_download_url': {'key': 'rootDownloadUrl', 'type': 'str'},
        'snapshots': {'key': 'snapshots', 'type': '{DownloadResourceInfo}'},
    }

    def __init__(self, **kwargs):
        super(SnapshotInfo, self).__init__(**kwargs)
        self.root_download_url = kwargs.get('root_download_url', None)
        self.snapshots = kwargs.get('snapshots', None)
