# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .training_output import TrainingOutput


class StructuredInterfaceOutputTrainingOutput(TrainingOutput):
    """StructuredInterfaceOutputTrainingOutput.

    :param training_output_type: Possible values include: 'Metrics', 'Model'
    :type training_output_type: str or ~designer.models.TrainingOutputType
    :param iteration:
    :type iteration: int
    :param metric:
    :type metric: str
    """

    _attribute_map = {
        'training_output_type': {'key': 'trainingOutputType', 'type': 'str'},
        'iteration': {'key': 'iteration', 'type': 'int'},
        'metric': {'key': 'metric', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(StructuredInterfaceOutputTrainingOutput, self).__init__(**kwargs)
