# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class StudioMigrationInfo(Model):
    """StudioMigrationInfo.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param source_workspace_id:
    :type source_workspace_id: str
    :param source_experiment_id:
    :type source_experiment_id: str
    :param source_experiment_link:
    :type source_experiment_link: str
    :param failed_node_id_list:
    :type failed_node_id_list: list[str]
    :ivar error_message:
    :vartype error_message: str
    """

    _validation = {
        'error_message': {'readonly': True},
    }

    _attribute_map = {
        'source_workspace_id': {'key': 'sourceWorkspaceId', 'type': 'str'},
        'source_experiment_id': {'key': 'sourceExperimentId', 'type': 'str'},
        'source_experiment_link': {'key': 'sourceExperimentLink', 'type': 'str'},
        'failed_node_id_list': {'key': 'failedNodeIdList', 'type': '[str]'},
        'error_message': {'key': 'errorMessage', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(StudioMigrationInfo, self).__init__(**kwargs)
        self.source_workspace_id = kwargs.get('source_workspace_id', None)
        self.source_experiment_id = kwargs.get('source_experiment_id', None)
        self.source_experiment_link = kwargs.get('source_experiment_link', None)
        self.failed_node_id_list = kwargs.get('failed_node_id_list', None)
        self.error_message = None
