# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TaskReuseInfo(Model):
    """TaskReuseInfo.

    :param experiment_id:
    :type experiment_id: str
    :param pipeline_run_id:
    :type pipeline_run_id: str
    :param node_id:
    :type node_id: str
    :param request_id:
    :type request_id: str
    :param run_id:
    :type run_id: str
    :param node_start_time:
    :type node_start_time: datetime
    :param node_end_time:
    :type node_end_time: datetime
    """

    _attribute_map = {
        'experiment_id': {'key': 'experimentId', 'type': 'str'},
        'pipeline_run_id': {'key': 'pipelineRunId', 'type': 'str'},
        'node_id': {'key': 'nodeId', 'type': 'str'},
        'request_id': {'key': 'requestId', 'type': 'str'},
        'run_id': {'key': 'runId', 'type': 'str'},
        'node_start_time': {'key': 'nodeStartTime', 'type': 'iso-8601'},
        'node_end_time': {'key': 'nodeEndTime', 'type': 'iso-8601'},
    }

    def __init__(self, *, experiment_id: str=None, pipeline_run_id: str=None, node_id: str=None, request_id: str=None, run_id: str=None, node_start_time=None, node_end_time=None, **kwargs) -> None:
        super(TaskReuseInfo, self).__init__(**kwargs)
        self.experiment_id = experiment_id
        self.pipeline_run_id = pipeline_run_id
        self.node_id = node_id
        self.request_id = request_id
        self.run_id = run_id
        self.node_start_time = node_start_time
        self.node_end_time = node_end_time
