# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UIParameterHint(Model):
    """UIParameterHint.

    :param ui_widget_type: Possible values include: 'Default', 'Mode',
     'ColumnPicker', 'Credential', 'Script'
    :type ui_widget_type: str or ~designer.models.UIWidgetTypeEnum
    :param column_picker:
    :type column_picker: ~designer.models.UIParameterHintColumnPicker
    :param ui_script_language: Possible values include: 'None', 'Python', 'R',
     'Json', 'Sql'
    :type ui_script_language: str or ~designer.models.UIScriptLanguageEnum
    """

    _attribute_map = {
        'ui_widget_type': {'key': 'uiWidgetType', 'type': 'str'},
        'column_picker': {'key': 'columnPicker', 'type': 'UIParameterHintColumnPicker'},
        'ui_script_language': {'key': 'uiScriptLanguage', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(UIParameterHint, self).__init__(**kwargs)
        self.ui_widget_type = kwargs.get('ui_widget_type', None)
        self.column_picker = kwargs.get('column_picker', None)
        self.ui_script_language = kwargs.get('ui_script_language', None)
