# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UIWidgetMetaInfo(Model):
    """UIWidgetMetaInfo.

    :param module_node_id:
    :type module_node_id: str
    :param meta_module_id:
    :type meta_module_id: str
    :param parameter_name:
    :type parameter_name: str
    :param ui_widget_type: Possible values include: 'Default', 'Mode',
     'ColumnPicker', 'Credential', 'Script'
    :type ui_widget_type: str or ~designer.models.UIWidgetTypeEnum
    """

    _attribute_map = {
        'module_node_id': {'key': 'moduleNodeId', 'type': 'str'},
        'meta_module_id': {'key': 'metaModuleId', 'type': 'str'},
        'parameter_name': {'key': 'parameterName', 'type': 'str'},
        'ui_widget_type': {'key': 'uiWidgetType', 'type': 'str'},
    }

    def __init__(self, *, module_node_id: str=None, meta_module_id: str=None, parameter_name: str=None, ui_widget_type=None, **kwargs) -> None:
        super(UIWidgetMetaInfo, self).__init__(**kwargs)
        self.module_node_id = module_node_id
        self.meta_module_id = meta_module_id
        self.parameter_name = parameter_name
        self.ui_widget_type = ui_widget_type
