# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .sub_pipelines_info_py3 import SubPipelinesInfo


class UnpackPackageFromCommunityRequestSubPipelinesInfo(SubPipelinesInfo):
    """UnpackPackageFromCommunityRequestSubPipelinesInfo.

    :param sub_graph_info:
    :type sub_graph_info: list[~designer.models.SubGraphInfo]
    :param node_id_to_sub_graph_id_mapping:
    :type node_id_to_sub_graph_id_mapping: dict[str, str]
    :param sub_pipeline_definition:
    :type sub_pipeline_definition:
     list[~designer.models.SubPipelineDefinition]
    """

    _attribute_map = {
        'sub_graph_info': {'key': 'subGraphInfo', 'type': '[SubGraphInfo]'},
        'node_id_to_sub_graph_id_mapping': {'key': 'nodeIdToSubGraphIdMapping', 'type': '{str}'},
        'sub_pipeline_definition': {'key': 'subPipelineDefinition', 'type': '[SubPipelineDefinition]'},
    }

    def __init__(self, *, sub_graph_info=None, node_id_to_sub_graph_id_mapping=None, sub_pipeline_definition=None, **kwargs) -> None:
        super(UnpackPackageFromCommunityRequestSubPipelinesInfo, self).__init__(sub_graph_info=sub_graph_info, node_id_to_sub_graph_id_mapping=node_id_to_sub_graph_id_mapping, sub_pipeline_definition=sub_pipeline_definition, **kwargs)
