# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WebServiceComputeMetaInfo(Model):
    """WebServiceComputeMetaInfo.

    :param node_count:
    :type node_count: int
    :param is_ssl_enabled:
    :type is_ssl_enabled: bool
    :param aks_not_found:
    :type aks_not_found: bool
    :param cluster_purpose:
    :type cluster_purpose: str
    :param public_ip_address:
    :type public_ip_address: str
    :param vm_size:
    :type vm_size: str
    :param location:
    :type location: str
    :param provisioning_state:
    :type provisioning_state: str
    :param state:
    :type state: str
    :param os_type:
    :type os_type: str
    :param id:
    :type id: str
    :param name:
    :type name: str
    :param created_by_studio:
    :type created_by_studio: bool
    :param is_gpu_type:
    :type is_gpu_type: bool
    :param resource_id:
    :type resource_id: str
    :param compute_type:
    :type compute_type: str
    """

    _attribute_map = {
        'node_count': {'key': 'nodeCount', 'type': 'int'},
        'is_ssl_enabled': {'key': 'isSslEnabled', 'type': 'bool'},
        'aks_not_found': {'key': 'aksNotFound', 'type': 'bool'},
        'cluster_purpose': {'key': 'clusterPurpose', 'type': 'str'},
        'public_ip_address': {'key': 'publicIpAddress', 'type': 'str'},
        'vm_size': {'key': 'vmSize', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'os_type': {'key': 'osType', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'created_by_studio': {'key': 'createdByStudio', 'type': 'bool'},
        'is_gpu_type': {'key': 'isGpuType', 'type': 'bool'},
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'compute_type': {'key': 'computeType', 'type': 'str'},
    }

    def __init__(self, *, node_count: int=None, is_ssl_enabled: bool=None, aks_not_found: bool=None, cluster_purpose: str=None, public_ip_address: str=None, vm_size: str=None, location: str=None, provisioning_state: str=None, state: str=None, os_type: str=None, id: str=None, name: str=None, created_by_studio: bool=None, is_gpu_type: bool=None, resource_id: str=None, compute_type: str=None, **kwargs) -> None:
        super(WebServiceComputeMetaInfo, self).__init__(**kwargs)
        self.node_count = node_count
        self.is_ssl_enabled = is_ssl_enabled
        self.aks_not_found = aks_not_found
        self.cluster_purpose = cluster_purpose
        self.public_ip_address = public_ip_address
        self.vm_size = vm_size
        self.location = location
        self.provisioning_state = provisioning_state
        self.state = state
        self.os_type = os_type
        self.id = id
        self.name = name
        self.created_by_studio = created_by_studio
        self.is_gpu_type = is_gpu_type
        self.resource_id = resource_id
        self.compute_type = compute_type
